### ISSUE TITLE
FROM resin/rpi-raspbian:wheezy

### ISSUE THREAD

**Issue by miekg** [hypriot/rpi-redis#1]
Hi, 

Thanks for the nice work in making docker easy on a RPI. The docker images them selves are all derived from rpi-raspbian which 55MB in size. I think it makes sense to support something like Alpine Linux, except that Alpine Linux only has packages for Raspberry 2 and not Raspberry 1 :(

**Comment by DieterReuter** [comment]
@miekg your right, but the `resin/rpi-raspbian` is already a very small base image with a full linux distro. Easy to start with, and your software will work without any large time efforts. 

If you'd like to build even smaller Docker images, you can look into Busybox or Alpine Linux - or you could build a super-small Docker image with a single Go binary. It just depends on the time you'd like to invest to get an optimised Docker image.  

With some more effort you can also tune a dynamically linked binary and look for all it's dependencies and include only these ones. Just look at this minimal Docker image [hypriot/rpi-busybox-httpd](https://github.com/hypriot/rpi-busybox-httpd) which is build with the help of the [dockerize](https://github.com/larsks/dockerize) tool.

**Comment by miekg** [comment]
Well, after _some_ effort I have: https://registry.hub.docker.com/u/miek/alpine-armv6l/ which seems to work :)
I've detailed the process on my [blog](http://miek.nl/posts/2015/May/25/Superslim%20Alpine%20Linux%20Image%20for%20Raspberry%20PI/) in case this is useful.

**Comment by miekg** [comment]
Docker images need to be small (I think), and a lot of people seem to be moving to Alpine linux as the base of theirs, so it makes sense to do the same here.

I, for one, don't expect to have a full blown linux distro at my disposal when I do a docker run.

Glad to help here, btw.

**Comment by alexellis** [comment]
@DieterReuter Can you explain the purpose of 'gosu' in some of the images? Thanks.

**Comment by alexellis** [comment]
@DieterReuter hey, what does gosu do in your images?

**Comment by DieterReuter** [comment]
@alexellis I've never used `gosu`, but maybe one of the authors of this repo can explain. /cc @Govinda-Fichtner @firecyberice

**Comment by StefanScherer** [comment]
Please use official redis image which is multi-arch and it should just work on ARM.

```
$ docker run --rm mplatform/mquery redis
Image: redis
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v5
   - linux/arm/v7
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x
```
