### ISSUE TITLE
No CA / SSL Certs (can't git clone etc)

### ISSUE THREAD

**Issue by alexellis** [hypriot/rpi-redis#2]
Hi chaps,

I can't download files from https websites with this image. Do you know if there is a package I can install with `apt-get` to get around this?

```
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': Problem with the SSL CA cert (path? access rights?)
package github.com/tools/godep: exit status 128
```

Thanks,

Alex

**Comment by alexellis** [comment]
```
apt-get install ca-certificates
```

?

**Comment by firecyberice** [comment]
This image provides only a redis database so there is no need for `git clone` and other packages.
If you would like to use it as base for developing you can easily create a new image with `FROM hypriot/rpi-redis`. But you can also develop in another container and link them together.

**Comment by alexellis** [comment]
OK I raised this on the wrong repo (window) - I meant to raise it against hypriot/rpi-raspbian, wrong window - but usually I'd check with the person who raised the bug before closing immediately.

**Comment by alexellis** [comment]
The image I wanted to mention was with the base image.. that you guys are using, not the redis container. I think I raised this on the wrong repo - but you don't have one for the base image.
